bee_input_excel:
    resource: "@BeeInputExcelBundle/Controller/"
    type:     annotation
    prefix:   /inputexcel

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /logout


